### ISSUE TITLE
Use toctoc with folder of *.md is possible ?

### ISSUE THREAD

**Issue by pnepe6** [n1k0/toctoc#2]
Hello, 

I want to know if its possible to specify a folder instead of README.md ?

**Comment by n1k0** [comment]
Not at this moment but feel free to open a PR.

**Comment by kopax** [comment]
@pnepe6 @n1k0 here it is: https://github.com/n1k0/toctoc/pull/4 :

- `<file>` accept a glob pattern
- `-s` option to prevent fail on missing TOC.

Could you release a new TOC version when changed will be approved?

**Comment by kopax** [comment]
Here it is : 

https://github.com/n1k0/toctoc/pull/4

Could you release a new TOC version if changed are approved?

**Comment by n1k0** [comment]
#4 has landed and toctoc v0.3.0 has been released to npm. Thanks!
