### ISSUE TITLE
toctoc is bad editing our readme.md

### ISSUE THREAD

**Issue by kopax** [n1k0/toctoc#7]
Our readme looks like this:

```

# email

blabla

## Table of Contents

  - [Documentation](#documentation)
  - [License](#license)

---
## Documentation

  - View [HTML documentation](https://google.com) *(require access)*

## License

MIT
```

Since a new version (I don't know which one), but building the readme in our precommit is editing the file wrongly.

We can find the markdown with

```
---## Documentation
```
 
or with tag

```
---    <-- tab here
## Documentation
```

This is how we have set our `package.json`:

```
+    "toctoc": "^0.3.0",
```

I don't want to blame anyone but the 0.3.1 came out a few days ago @n1k0  =] 

Can you please fix this or just tell us the new valid format ?

**Comment by n1k0** [comment]
Thanks for the report. v0.3.2 has just been published with a fix.
